### ISSUE TITLE
Clicking on Thaumic Reinforced Void Jar in NEI Crashes Client

### ISSUE THREAD

**Issue by shawnbyday** [kekzdealer/KekzTech#22]
I'm on 2.0.9.0 dev2 and I run my world on a private server.

When clicking on Thaumic Reinforced Void Jar in NEI (to view recipe) it crashes my client.

Here is a link to my log: https://paste.ee/p/ZlHZt

For the record I don't have the recipe researched currently so that might be some sort of indicator for troubleshooting.

**Comment by kekzdealer** [comment]
Closing because no one can replicate it
