### ISSUE TITLE
[TFFT] Not re-forming after changing layout

### ISSUE THREAD

**Issue by TimDiekmann** [kekzdealer/KekzTech#4]
The multiblock does not re-calculate it's structure, after it's built once. I have to remove a few blocks before, wait for "Incomplete structure", then re-place the removed blocks. Otherwise, new blocks are not recognized (like hatches or storage fields).

**Comment by kekzdealer** [comment]
I'm aware of this issue and I sadly do not have any solution for it. 
I have managed to force the controller to run the check again by placing a dirt block in front of it and destroying it again.

**Comment by TimDiekmann** [comment]
That's a better workaround as removing some casings, inserting a hatch, removing the hatch and re-add the casings at least, thanks!

**Comment by kekzdealer** [comment]
Fixed by bart: https://github.com/kekzdealer/KekzTech/pull/14#issue-407417692
