### ISSUE TITLE
[TFFT] Extracting fluids via the Multi-Fluid I/O hatches cannot be filtered

### ISSUE THREAD

**Issue by TimDiekmann** [kekzdealer/KekzTech#5]
I tried exporting fluids via the ender fluid conduits from EIO. However, it's not possible to filter those. By now I only discovered water to work, every other fluid like Benzene or Nitrogen don't work.

**Comment by kekzdealer** [comment]
Are you trying to have the multi fluid hatch export into an ender fluid conduit with a whitelist filter applied at the source side of the conduit?

Ender fluid conduits only ever try to export the first fluid they can aquire, so the above isn't supported on eIO's side.

**Comment by TimDiekmann** [comment]
> Are you trying to have the multi fluid hatch export into an ender fluid conduit with a whitelist filter applied at the source side of the conduit?

Yes, I have tried both

> Ender fluid conduits only ever try to export the first fluid they can aquire, so the above isn't supported on eIO's side.

Oh good to know! Well, that's my first tank with multiple inputs ;)

**Comment by albus12138** [comment]
Is ender fluid conduit cannot work with TFFT in any condition?
I applied a whitelist filter to my ender conduit, it works well when target fluid in slot 0. But after this fluid used up and input again, the fluid stored into slot 3, ender conduit cannot export this fluid.
I use TFFT Multi-Fluid IO Hatch and Ender Conduit.
Is there an alternative design?

**Comment by kekzdealer** [comment]
That is exactly the case outlined in my last message. 
No, I am not aware of any other solution to this as if right now.
